name: circular_motion
description: A package to create a circular positioned widgets and can be scrolled to rotate them in the desired circular way.
version: 0.0.6
homepage: https://github.com/lewiseman/circular_motion
issue_tracker: https://github.com/lewiseman/circular_motion/issues

environment:
  sdk: ">=2.18.0 <4.0.0"
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
