name: circular_motion
description: A package to create a circular positioned widgets and can be scrolled to rotate them in the desired circular way.
version: 0.0.1
homepage: https://github.com/lewiseman/circular_motion
issue_tracker: https://github.com/lewiseman/circular_motion/issues

environment:
  sdk: ">=2.17.1 <3.0.0"
  flutter: ">=1.17.0"
 
dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0


flutter:
